# Generated by Django 2.0.7 on 2019-10-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('walk', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('dung', models.CharField(max_length=200)),
                ('Pee', models.CharField(max_length=200)),
                ('morning', models.BooleanField()),
                ('morning_amount', models.IntegerField()),
                ('lunch', models.BooleanField()),
                ('lunch_amount', models.IntegerField()),
                ('dinner', models.BooleanField()),
                ('dinner_amount', models.IntegerField()),
                ('shower', models.BooleanField()),
                ('medicine', models.CharField(max_length=200)),
                ('puke', models.CharField(max_length=200)),
                ('behavior', models.CharField(max_length=200)),
                ('record', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('medicine', models.CharField(blank=True, max_length=200)),
                ('next_date', models.DateTimeField(blank=True, verbose_name='date published')),
                ('price', models.IntegerField()),
                ('record', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('food', models.CharField(blank=True, max_length=200)),
                ('health', models.CharField(blank=True, max_length=200)),
                ('record', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=200)),
                ('count', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('record', models.TextField(blank=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Dog'),
        ),
        migrations.AddField(
            model_name='dailylife',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Dog'),
        ),
    ]
