# Generated by Django 2.0.7 on 2019-10-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='food',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='health',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Dog'),
        ),
        migrations.AddField(
            model_name='health',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Dog'),
        ),
        migrations.AddField(
            model_name='food',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Dog'),
        ),
    ]
