# Generated by Django 2.0.7 on 2019-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20191021_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylife',
            name='Pee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='behavior',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='dinner_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='dung',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='lunch_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='medicine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='morning_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='puke',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='walk',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
