# Generated by Django 2.0.7 on 2019-10-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20191026_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylife',
            name='dinner_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='lunch_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='morning_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='walk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
