# Generated by Django 2.0.7 on 2019-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20191026_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
