# Generated by Django 2.0.7 on 2019-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(default="{% static 'main_img01.jpg' %}", null=True, upload_to='images/'),
        ),
    ]
