# Generated by Django 2.0.7 on 2019-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_dog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylife',
            name='dinner',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='lunch',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='morning',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='shower',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='walk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailylife',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='next_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
