# Generated by Django 2.0.7 on 2019-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20191028_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
